/**
 * stm32_encoder_force.c
 *
 * Reads:
 *   - AS5600 magnetic encoder via I2C (address 0x36)
 *   - HX711 load cell amplifier via bit-banged GPIO
 *
 * Streams CSV over USB Serial (UART):
 *   timestamp_ms,angle_deg,force_raw
 *
 * Target: STM32C092RC
 * Assumes STM32CubeIDE / HAL generated project with:
 *   - I2C1 enabled (SDA/SCL with external 10k pull-ups)
 *   - UART configured for USB Serial (e.g. USART2 or CDC)
 *   - Two free GPIO pins for HX711 (DOUT, SCK)
 *
 * Drop this logic into your main.c after the MX_xxx_Init() calls.
 */

#include "main.h"
#include <stdio.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/*  USER CONFIG — adjust to match your CubeMX pin assignments          */
/* ------------------------------------------------------------------ */

/* I2C handle generated by CubeMX */
extern I2C_HandleTypeDef hi2c1;

/* UART handle for USB serial */
extern UART_HandleTypeDef huart1;

/* HX711 GPIO */
#define HX711_DOUT_PORT   GPIOC
#define HX711_DOUT_PIN    GPIO_PIN_9   /* Data out from HX711 */
#define HX711_SCK_PORT    GPIOC
#define HX711_SCK_PIN     GPIO_PIN_8   /* Clock to HX711      */

/* AS5600 */
#define AS5600_I2C_ADDR   (0x36 << 1)  /* HAL uses 8-bit address */
#define AS5600_REG_ANGLE_H 0x0E        /* High byte of raw angle */

/* Streaming interval */
#define STREAM_INTERVAL_MS  20         /* 50 Hz */

/* ------------------------------------------------------------------ */
/*  AS5600 — read 12-bit angle (0–4095 = 0–360°)                      */
/* ------------------------------------------------------------------ */
static uint16_t AS5600_ReadRawAngle(void)
{
    uint8_t buf[2] = {0};
    /* Point to angle register then read 2 bytes */
    uint8_t reg = AS5600_REG_ANGLE_H;
    HAL_I2C_Master_Transmit(&hi2c1, AS5600_I2C_ADDR, &reg, 1, 10);
    HAL_I2C_Master_Receive (&hi2c1, AS5600_I2C_ADDR, buf, 2, 10);
    return ((uint16_t)(buf[0] & 0x0F) << 8) | buf[1];
}

static float AS5600_RawToDegrees(uint16_t raw)
{
    return (raw / 4096.0f) * 360.0f;
}

/* ------------------------------------------------------------------ */
/*  HX711 — bit-banged 24-bit read, gain=128 channel A (default)      */
/* ------------------------------------------------------------------ */
static int32_t HX711_Read(void)
{
    /* Wait for DOUT to go LOW (data ready), with a simple timeout */
    uint32_t timeout = HAL_GetTick() + 100;
    while (HAL_GPIO_ReadPin(HX711_DOUT_PORT, HX711_DOUT_PIN) == GPIO_PIN_SET)
    {
        if (HAL_GetTick() > timeout) return 0;  /* timeout — return 0 */
    }

    int32_t data = 0;

    /* Clock in 24 bits */
    for (int i = 0; i < 24; i++)
    {
        HAL_GPIO_WritePin(HX711_SCK_PORT, HX711_SCK_PIN, GPIO_PIN_SET);
        __NOP(); __NOP(); __NOP(); /* short pulse ~1 µs */
        data = (data << 1) | HAL_GPIO_ReadPin(HX711_DOUT_PORT, HX711_DOUT_PIN);
        HAL_GPIO_WritePin(HX711_SCK_PORT, HX711_SCK_PIN, GPIO_PIN_RESET);
        __NOP(); __NOP(); __NOP();
    }

    /* 25th pulse — sets gain=128 channel A for next reading */
    HAL_GPIO_WritePin(HX711_SCK_PORT, HX711_SCK_PIN, GPIO_PIN_SET);
    __NOP(); __NOP(); __NOP();
    HAL_GPIO_WritePin(HX711_SCK_PORT, HX711_SCK_PIN, GPIO_PIN_RESET);
    __NOP(); __NOP(); __NOP();

    /* Sign-extend 24-bit two's complement to int32 */
    if (data & 0x800000) data |= 0xFF000000;

    return data;
}

/* ------------------------------------------------------------------ */
/*  UART transmit helper                                               */
/* ------------------------------------------------------------------ */
static void UART_Print(const char *str)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)str, strlen(str), 50);
}

/* ------------------------------------------------------------------ */
/*  Main streaming loop — call this from your main() after init        */
/* ------------------------------------------------------------------ */
void EncoderForce_Stream(void)
{
    char buf[64];
    uint32_t last_tick = 0;

    /* Send CSV header so Python knows the column order */
    UART_Print("timestamp_ms,angle_deg,force_raw\r\n");

    while (1)
    {
        uint32_t now = HAL_GetTick();
        if ((now - last_tick) >= STREAM_INTERVAL_MS)
        {
            last_tick = now;

            uint16_t raw_angle = AS5600_ReadRawAngle();
            float    angle_deg = AS5600_RawToDegrees(raw_angle);
            int32_t  force_raw = HX711_Read();

            /* Format: "1234,180.52,-30412\r\n" */
            snprintf(buf, sizeof(buf), "%lu,%.2f,%ld\r\n",
                     (unsigned long)now, angle_deg, (long)force_raw);
            UART_Print(buf);
        }
    }
}
